### ISSUE TITLE
lglc.exe fails to install on windows 7

### ISSUE THREAD

**Issue by atomman** [franapoli/pyleaf#6]
![image](https://cloud.githubusercontent.com/assets/10225003/13697860/ac65c7e6-e770-11e5-8569-6bf46cc51af8.png)

**Comment by franapoli** [comment]
Hi atomman,
thank you for the report. As mentioned at http://www.francesconapolitano.it/leaf/download.html (reachable from the lgl github page), the missing libraries required by MS Windows are publicly available. You should be able to easily download and add them to your system. Let me know if you have problems in the process.

**Comment by franapoli** [comment]
Thanks for the report.
This is actually an lgl issue (there's an [lgl github project](https://github.com/franapoli/lglc) too). The missing libraries are publicly available and you should be able to easily find and install them (your missing one is [here](http://www.dll-files.com/dllindex/dll-files.shtml?libgcc_s_dw2-1)).

**Comment by atomman** [comment]
Hi
Thank you for the feedback.
I got the missing .dll files but running the ex1.py as described in the
tutorial gives no output but no error either. The lglc.exe is on the path.

Any idea what might be wrong?

Thanks,


Den fredag den 11. marts 2016 skrev Francesco Napolitano <
notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:

> Thanks for the report.
> This is actually an lgl issue (there's an lgl github project
> <https://github.com/franapoli/lglc> too). The missing libraries are
> publicly available and you should be able to easily find and install them
> (your missing one is here
> <http://www.dll-files.com/dllindex/dll-files.shtml?libgcc_s_dw2-1>).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/franapoli/pyleaf/issues/6#issuecomment-195310866>.
>


-- 
Sent from Gmail Mobile

**Comment by atomman** [comment]
I got it! Look forward to get more familiar with the tool and apply it in
my work

Thanks!

Den fredag den 11. marts 2016 skrev Francesco Napolitano <
notifications@github.com>:

> Thanks for the report.
> This is actually an lgl issue (there's an lgl github project
> <https://github.com/franapoli/lglc> too). The missing libraries are
> publicly available and you should be able to easily find and install them
> (your missing one is here
> <http://www.dll-files.com/dllindex/dll-files.shtml?libgcc_s_dw2-1>).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/franapoli/pyleaf/issues/6#issuecomment-195310866>.
>


-- 
Sent from Gmail Mobile

**Comment by franapoli** [comment]
Hope you enjoy it.
cheers
